{{- if .Values.museum.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ente-photos.museum.fullname" . }}
  labels:
    {{- include "ente-photos.museum.labels" . | nindent 4 }}
  {{- with .Values.museum.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.museum.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.museum.ingress.tls }}
  tls:
    {{- range .Values.museum.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.museum.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "ente-photos.museum.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
