apiVersion: v1
kind: Service
metadata:
  name: {{ include "ente-photos.museum.fullname" . }}
  labels:
    {{- include "ente-photos.museum.labels" . | nindent 4 }}
  {{- with .Values.museum.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.museum.service.type }}
  {{- with .Values.museum.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.museum.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.museum.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.museum.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.museum.service.type "NodePort") .Values.museum.service.nodePort }}
      nodePort: {{ .Values.museum.service.nodePort }}
      {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port | default 2112 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "ente-photos.museum.selectorLabels" . | nindent 4 }}
